### ISSUE TITLE
Set up GitHub actions

### ISSUE THREAD

**Issue by DavAug** [SABS-R3-Epidemiology/seirmo#1]
- [x] Set up unit tests for different python versions.
- [x] Set up unit tests for different operating systems.
- [x] Set up unit tests coverage test.
- [ ] Set up sphinx documentation test.
- [x] Set up copyright tests.
- [x] Set up flake8 tests.

**Comment by DavAug** [comment]
For some inspiration:
https://github.com/pints-team/pints/tree/master/.github/workflows

They use run-tests.py to execute the tests.
https://github.com/pints-team/pints/blob/master/run-tests.py

**Comment by siting-miao** [comment]
Sphinx documentation test to be addressed in #8

**Comment by DavAug** [comment]
Setting up the docstring tests has been moved to a separate issue #19 .
