### ISSUE TITLE
Set up doc string tests

### ISSUE THREAD

**Issue by DavAug** [SABS-R3-Epidemiology/seirmo#19]
Create a GitHub actions that tests that all classes and functions are registered with sphinx.

Feel free to have a look at how pints solved this:
Workflow: https://github.com/pints-team/pints/blob/master/.github/workflows/docs-test.yml
Run-tests.py: https://github.com/pints-team/pints/blob/master/run-tests.py

- [x] The `run_doctests` can be kept, but the internal `doctest_examples_readme` function can be removed for now.
- [x] The `doctest_sphinx` can be copied as it is.
- [x] The `doctest_rst_and_public_interface` is important but needs to be adapted to match our repository structure, i.e. only import `seimo` for now (instead of the pints modules).
- [x] copy the `get_all_documented_symbols` as is.
- [x] copy the `check_exposed_symbols` as is.

**Comment by FarmHJ** [comment]
Checking that all classes and methods are documented in an RST file and that public interfaces are clean.
The following classes do not appear in any RST file:
  undocumented class: seirmo.models.ForwardModel
  undocumented class: seirmo.models.SEIRModel
FAILED

I had this error when running the doc string test. I updated the modules in the index.rst. I don't know how to resolve this.

**Comment by FarmHJ** [comment]
Close with #31
