### ISSUE TITLE
Create Jupyter notebook to demonstrate simulation of SEIR model

### ISSUE THREAD

**Issue by DavAug** [SABS-R3-Epidemiology/seirmo#20]
In this issue we will address task 1 in the [exercise sheet](https://benlambertdotcom.files.wordpress.com/2020/10/week_project.docx) with a simple Jupyter notebook.

- [x] Create a directory `examples` in the root directory.
- [x] Create a Jupyter notebook in the `examples` directory called `basic_simulation.ipynb`.
- [x] Use the `SEIRModel` class to simulate the model for some set of parameters and times.
- [x] Visualise the simulation with a plotly line graph, e.g. https://plotly.com/python/line-charts/. Make sure to provide appropriate axis labels with units.
- [x] Render the notebook with nbviewer https://nbviewer.jupyter.org/
- [x] Create a README.md in the `examples` directory with the header `Examples` and list of examples notebooks that reference the nbviewer rendered notebook.

**Comment by siting-miao** [comment]
> In this issue we will address task 1 in the [exercise sheet](https://benlambertdotcom.files.wordpress.com/2020/10/branching-process-models-handout.pdf) with a simple Jupyter notebook.
> 
> * [ ]  Create a directory `examples` in the root directory.
> * [ ]  Create a Jupyter notebook in the `examples` directory called `basic_simulation.ipynb`.
> * [ ]  Use the `SEIRModel` class to simulate the model for some set of parameters and times.
> * [ ]  Visualise the simulation with a plotly line graph, e.g. https://plotly.com/python/line-charts/. Make sure to provide appriate axis labels with units.
> * [ ]  Render the notebook with nbviewer https://nbviewer.jupyter.org/
> * [ ]  Create a README.md in the `examples` directory with the header `Examples` and list of examples notebooks that reference the nbviewer rendered notebook.

Just a minor thing. The exercise sheet linked seems to be the one for branchpro :)

**Comment by siting-miao** [comment]
@DavAug I don't know why the figure is not showing up in the Jupyter notebook?

**Comment by DavAug** [comment]
That is because you’ll have to safe the widget state in order for it to show up (sorry! I didn’t mention that before) let’s chat about it at 4pm?

Best,
David

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by siting-miao** [comment]
That will be great! See you soon.

Sincerely,

Siting

________________________________

**Comment by DavAug** [comment]
> > In this issue we will address task 1 in the [exercise sheet](https://benlambertdotcom.files.wordpress.com/2020/10/branching-process-models-handout.pdf) with a simple Jupyter notebook.
> > 
> > * [ ]   Create a directory `examples` in the root directory.
> > * [ ]   Create a Jupyter notebook in the `examples` directory called `basic_simulation.ipynb`.
> > * [ ]   Use the `SEIRModel` class to simulate the model for some set of parameters and times.
> > * [ ]   Visualise the simulation with a plotly line graph, e.g. https://plotly.com/python/line-charts/. Make sure to provide appriate axis labels with units.
> > * [ ]   Render the notebook with nbviewer https://nbviewer.jupyter.org/
> > * [ ]   Create a README.md in the `examples` directory with the header `Examples` and list of examples notebooks that reference the nbviewer rendered notebook.
> 
> Just a minor thing. The exercise sheet linked seems to be the one for branchpro :)

Thank you! I corrected the link.
