### ISSUE TITLE
Register the ForwardModel class and the SEIRModel class with Sphinx

### ISSUE THREAD

**Issue by DavAug** [SABS-R3-Epidemiology/seirmo#23]
Register the ForwardModel and SEIRModel class with Sphinx (by again peaking at what pints did). See https://github.com/pints-team/pints/tree/master/docs/source .

- [x] Add a `contents` section to the index.rst with an item called `models`
- [x] Create a `models.rst` in the same directory that refers to the ForwardModel and SEIRModel using the following syntax
```
.. currentmodule:: seirmo

<Some text with a brief explanation what models are one might find here (but not too specific as we may add other models later)>

Overview:

- :class:`ForwardModel`
- :class:`SEIRModel`


.. autoclass:: ForwardModel

.. autoclass:: SEIRModel
```

**Comment by FarmHJ** [comment]
#19

**Comment by DavAug** [comment]
I think the issue here is probably that we didn't update the `conf.py`, see how the branchpro repo solved this
https://github.com/SABS-R3-Epidemiology/branchpro/blob/main/docs/source/conf.py

**Comment by FarmHJ** [comment]
Close with #31
