### ISSUE TITLE
Create a Jupyter notebook that demonstrates how the incidence number can be simulated with the SEIR model

### ISSUE THREAD

**Issue by DavAug** [SABS-R3-Epidemiology/seirmo#25]
This requires #24 to be completed.

In this issue we will address task 1 in the [exercise sheet](https://benlambertdotcom.files.wordpress.com/2020/10/branching-process-models-handout.pdf) with a simple Jupyter notebook, similar to #20 . The main difference is that instead of plottling the trajectory of S, E, I, R, we will plot the incidence number in a bar plot.

- [x] Create a Jupyter notebook in the `examples` directory called `incidence_simulation.ipynb`.
- [x] Use the `SEIRModel` class to simulate the incidence number for some set of parameters and times.
- [x] Visualise the simulation with a plotly bar graph, e.g. https://plotly.com/python/bar-charts/. Make sure to provide appopriate axis labels with units.
- [x] Add a reference to the nbviewer rendered notebook to the examples README.md.

**Comment by siting-miao** [comment]
@DavAug It is really weird that when I copy the link of this notebook to nbviewer, the document cannot be found, while this works for the basic simulation before.

**Comment by DavAug** [comment]
Hmm we’ll figure it out. Just work out the tasks locally and we’ll fix it after.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by siting-miao** [comment]
@DavAug I am thinking about the way we compute the incidence number. The way we compute it makes it compulsory to make the time step to solve the ODEs be 1 (say we want the incidence per day), will this make the error in incidence be significant?

**Comment by siting-miao** [comment]
> Hmm we’ll figure it out. Just work out the tasks locally and we’ll fix it after. Get Outlook for iOS<https://aka.ms/o0ukef>
> […](#)

@DavAug That would be great! Thank you so much.

**Comment by DavAug** [comment]
> @DavAug I am thinking about the way we compute the incidence number. The way we compute it makes it compulsory to make the time step to solve the ODEs be 1 (say we want the incidence per day), will this make the error in incidence be significant?

That is correct! What we are doing is: we compute the incidence number between the provided time points, that can be days weeks, months, or even some irregular and uneven intervals. That gives the user the freedom to explore the incidences within any desired time interval. 

The ODE solver actually does many more steps internally, but then just returns the specified time points. Does that make sense? 

Please let me know whether I failed to answer your question. I am not sure I fully understood it :D

**Comment by siting-miao** [comment]
Dear David,

Yeah that fully answers my question. It will not be a problem if the solver actually takes much more points in the time interval. Thank you so much!

Sincerely,

Siting
________________________________
