### ISSUE TITLE
Docs still buggy

### ISSUE THREAD

**Issue by DavAug** [SABS-R3-Epidemiology/seirmo#33]
The ForwardModel and SEIRModel are not listed on the docs, but somehow the details of the API are not displayed. 

Let's have a look what the branchpro group did to fix this.

**Comment by FarmHJ** [comment]
I tried to follow everything the branchpro group did but it is still not working and I don't know why

**Comment by FarmHJ** [comment]
I added a requirements-doc.txt in the Github and on the Readthedocs portal because it said 'No module named numpy' previously. It is working now but the requirements file is very long, maybe there's a way to tidy it? The branchpro group had a really short one of 3 lines.
