### ISSUE TITLE
Create an incidence number simulation app

### ISSUE THREAD

**Issue by DavAug** [SABS-R3-Epidemiology/seirmo#34]
Create a dash app that allows us to simulate the incidence number for different parameter values.

It's ok to first implement a version without thinking about software engineering, but feel free to try to do it in a software enginnering manner.

The app should 

- [ ] create a plot of the incidence number over time.
- [ ]  have a number of parameter sliders for each model parameter.

I suggest you start with the slider example here: https://dash.plotly.com/basic-callbacks

and use our model and simulation controller to run the simulation.

If you'd like to try this in a software engineering way right away, follow the principle of one class for one task. In this case that could mean:

- [ ] Implement a figure class that sets up the layout of the figure, and has a method to add the data as a bar chart, and a method to show the figure, see #36 .
- [ ] Implement a class for the slider groups, which arranges the sliders and gives them labels, such that you know which slider connects to which parameter. This class should have a method to add a slider with a label, see #37 .
- [ ] Extend the SimulationController to instantiate a dash app with an instance of the figure class and an instance of the slider group. Implement methods to add the data, which updates the figure, and a method to add a model, which updates the slider group to contain one parameter for each slider.
- [ ] Implement the callback external to the SimulationController.

**Comment by FarmHJ** [comment]
Done in #38
