### ISSUE TITLE
Create an IncidenceNumberSimulationApp

### ISSUE THREAD

**Issue by DavAug** [SABS-R3-Epidemiology/seirmo#38]
Extending #34 .

Create an IncidenceNumberSimulationApp that

- [x] instantiates with an empty IndcidenceNumberPlot
- [x] instantiates with an empty SlidersComponent
- [x] arranges those empty classes using [Dash Bootstrap Components](https://dash-bootstrap-components.opensource.faculty.ai/). How you arrange them is up to you. A natural choice may be to have the figure on the left and the sliders/buttons on the right. This can be done by
     - [x] Create a `dbc.Container` (this just defines a box on the website in which the figure and the sliders will be placed, i.e. leave enough space to the left and right for different screen sizes.)
     - [x] Within this container create a `dbc.Row` which makes sure that both, the figure and the slider/button group are aligned horizontally
     - [x] Within this row define one `dbc.Column` for the figure and one `dbc.Column` for the slider/button group, and the respective `dcc.Graph` and slider component object to the column.
     - [x] Instantiate also with a default for the simulation times.
- [x] Implement an add_data method that adds the data to the figure and sets the axis labels according to the dataframe keys.
- [x] Implement an add_model method which
    - [x] Goes through the parameters of the model and creates a slider for each of them (feel free to set min, max and initial value to be all the same for now)
   - [x] Add a plot of the simulation for the initial slider values to the figure.
- [x] Implement a method that returns the slider ids of the sliders
- [x] Implement an update_simulation method which
     - [x] Simulates the model for some input parameters
     - [x] Replaces the y values of the simulation trace with the newly simulated values. (Do you know why adding the simulation trace wouldn't work as expected?)
- [ ] The callback has t be implemented externally to the class, but test that 
```
sliders = app.slider_ids()

@app.app.callback(
        Output('fig', 'figure'),
        [Input(s, 'value') for s in sliders])
    def update_simulation(*args):
        """
        Simulates the model for the current slider values and updates the
        model plot in the figure.
        """
        parameters = args
        fig = app.update_simulation(parameters)

        return fig
```
works as expected. Here `fig` is the figure id and `sliders` are the slider ids in the same order as the input parameters of the simulation.

**Comment by FarmHJ** [comment]
#44 Completed
