### ISSUE TITLE
Decide whether _SliderComponent class should be private or public

### ISSUE THREAD

**Issue by DavAug** [SABS-R3-Epidemiology/seirmo#41]
At the moment the _SliderComponent is private (based on the leading '_') but nevertheless registered in the docs, which makes the class pretty much public. Decide to go with one or the other but be consistent:

Either
- [ ] Rename `_SliderComponent` to `SliderComponent` and keep it in the docs.

or

- [x] Keep `_SliderComponent` as `_SliderComponent`, but remove it from the docs.

**Comment by FarmHJ** [comment]
Issue solved and merged
