### ISSUE TITLE
Refactor group sliders method

### ISSUE THREAD

**Issue by DavAug** [SABS-R3-Epidemiology/seirmo#42]
The SliderComponent class has a method that `group_sliders`, that takes a bunch of slider_ids and returns the correpsonding dcc.Sliders as a html.Div. 

A possibly more flexible implementation separates grouping and html.Div creating. Imagine you could create multiple groups of sliders by calling `group_sliders` a number of times, and return the final html.Div in one go by calling another method subsequently.

- [ ] Refactor `group_sliders` to have the same inputs, but instead of creating and returning an html.Div you save the group_ids and slider_ids in a dictionary {'group_id': [slider_id 1, slider_id 2, ...]}.
- [ ] When calling `group_sliders` check that the group_id is not already in the dictionary.
- [ ] When calling `group_sliders` check that the slider ids are not already in the dictionary.
- [ ] Implement a method `get_slider_component` (or implement it as the `__call__` method of the class), that creates a html component from the dictionary
    - [ ] Create one block for each slider group
    - [ ] Label the block by the group id
    - [ ] Define a little separation between the slider groups (by setting the bottom-margin)
    - [ ] Fill the block with the associated sliders.
- [ ] Return the final html component

**Comment by FarmHJ** [comment]
Refactored slider class
