### ISSUE TITLE
Create a SubplotFigure

### ISSUE THREAD

**Issue by DavAug** [SABS-R3-Epidemiology/seirmo#47]
This class accepts any class accepts instances from the seirmo.IncidenceNumberPlot and seirmo.TimeSeriesPlot. (We can extend this class later to allow for any number of rows and columns, but for now):

- [x] Instantiate with and seirmo.IncidenceNumberPlot class and a seirmo.TimeSeriesPlot class and save the instantiated plots to private variables
- [x] Use plotly.subplots. make_subplots to create a figure with 1 column and 2 rows. Let the top subplot be the IncidenceNumberPlot and the bottom one the TimeSeriesPlot.
- [x] Write a private method that gets the layout from the IncidenceNumberPlot and the TimeSeriesPlot and sets the labels of the subplots.
- [x] Write a private method that gets the traces from the IncidenceNumberPlot and the TimeSeriesPlot and adds them to the subplots.
- [x] Create an add data method which accepts a dataframe and optional key labels time_key, inc_key, pop_keys with default similar to the  seirmo.IncidenceNumberPlot class and the seirmo.TimeSeriesPlot class. Set the labels according to those keys and add the data by using the add_data methods from the plots and using the private methods from above.
- [x] Create an add_simulation similar to above.
- [x] Create a show method.

**Comment by FarmHJ** [comment]
#56 Completed
