### ISSUE TITLE
Extend SEIRModel

### ISSUE THREAD

**Issue by DavAug** [SABS-R3-Epidemiology/seirmo#66]
- [x] Remove ForwardModel base class
- [x] Let SEIRModel inherit from pints.ForwardModel
- [x] Init assigns default output_names, n_output, n_parameters
- [x] implement n_outputs and n_parameters according to pints.ForwardModel
- [x] implement set_outputs which can be used to select any subset of outputs (S, E, I, R or n_incidences)
- [x] implement ``output_names`` which returns the output names (selected outputs)
- [x] Refactor ``simulate`` to return set outputs only and remove flag return_incidences

**Comment by FarmHJ** [comment]
#68 Completed
