### ISSUE TITLE
Implement ReducedModel class

### ISSUE THREAD

**Issue by DavAug** [SABS-R3-Epidemiology/seirmo#67]
The ReducedModel can be used to fix model parameters of a ForwardModel.

- [x] Takes a ForwardModel
- [x] has a method called fix_parameters which takes a dict of parameter names and values.
- [x] Otherwise behaves exactly the same as a ForwardModel
- [x] Write tests

**Comment by DavAug** [comment]
@siting-miao @FarmHJ I gave this a go just now, simply to make this a little bit easier. I leave writing tests to you ;)

**Comment by FarmHJ** [comment]
#73 Completed
