### ISSUE TITLE
Optimisation app

### ISSUE THREAD

**Issue by DavAug** [SABS-R3-Epidemiology/seirmo#74]
Write an app that finds the maximum a posteriori (MAP) estimates for the flu dataset.

- [x] Implement a _OptimisationApp in file _optimisation_app.py
- [x] The layout is similar to simulation app but sliders are replaced by a button.
- [x] implement a `add_problem` method to the app that takes the data as `pandas.DataFrame`, add the model as a `seirmo.ForwardModel` which
   - [x] visualizes the data  in the figure
   - [x] sets up the simulation controller for the model and the data time range
   - [x] defines the log-posterior for hard-coded priors and likelihoods.
   - [x] sets up the OptimisationController for a `pints.CMAES`, from prior drawn initial point, log-transformed parameters and otherwise default settings.
- [x] We keep the `update_simulation` from the simulation app.
- [x] implement a callback that connects to the button and executes the optimisation.run and adds the simulation for the optimized parameters to the figure.

**Comment by DavAug** [comment]
As discussed it is probably best if we select the data from index 60 to 90 and normalise by units of 100k incidences. If we choose priors similar to this (Happy to choose Truncated Gaussians instead) we should be able to reliably find the optimum https://nbviewer.jupyter.org/github/SABS-R3-Epidemiology/seirmo/blob/optimiation-notebook/examples/optimisation.ipynb. 

The minimal optimisation app should probably fix the parameters similar to the notebook. As an extension we can allow to fix any parameter (which may be used to illustrate that the model is not identifiable).

**Comment by FarmHJ** [comment]
#80 Completed
